
language: rust
rust:
  - nightly
install:
  - |
    if [ ! -d "$HOME/.elan/toolchains/" ]; then
      curl https://raw.githubusercontent.com/Kha/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain 3.4.2 -y
    fi
  - source ~/.elan/env

script:
  - cargo build
  - sh run_tests.sh
  - cargo build --release
  - mv target/release/olean-rs target/release/olean-rs-linux
deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: target/release/olean-rs-linux
  skip_cleanup: true
  on:
    tags: true
