[package]
name = "olean-rs"
version = "0.1.0"
authors = ["Mario Carneiro <di.gama@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
num-traits = "0.2.6"
num-derive = "0.2.3"
byteorder = "1.2.7"
lazy_static = "1.2.0"
stacker = "0.1"
